### ISSUE TITLE
Referencing file paths

### ISSUE THREAD

**Issue by dmehrab06** [snap-stanford/covid-mobility#1]
Would it be possible to add a section in the README regarding which part of the codes need to be changed in order to properly specify file paths? At first, I thought it was only the `covid_constants_and_utils.py` file. But, I saw some other files make references to filepaths as well.

**Comment by serinachang5** [comment]
Thanks for this suggestion! We've refactored all file directories so that they are defined in `covid_constants_and_utils.py`. Specific filenames are still referenced in other files, following their naming constructs in the raw downloaded data (e.g., `os.path.join(PATH_TO_SDM_V1, dt.strftime('%Y/%m/%d/%Y-%m-%d-social-distancing.csv.gz'))` in `helper_methods_for_aggregate_data_analysis.py`), which we will also note in the README.
